name: Main

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install
      - name: Run format
        run: pnpm format
      - name: Check diff
        run: git diff --exit-code
